package org.shop.classes;

import org.shop.interfaces.Convertible;
import org.shop.interfaces.DbcAdapter;
import java.lang.String;
public class DbcAdapterRecordString implements DbcAdapter<String> {

    DatabaseConnector db = DatabaseConnector.getInstance();

    /**
     * Database returns String, but we want String[]
     * */
    @Override
    public String loadData(int id, Class convertible) {
        DatabaseConnector db = DatabaseConnector.getInstance();
        return db.loadData(id, convertible);
    }

    /**
     * DB already uses string as generated by most convertibles
     */
    @Override
    public String adaptDataToDBFormat(String string) {
        return string;
    }

    @Override
    public void updateInBase(Convertible convertible) {
        db.updateRecord(convertible);
    }

}
